codehouseindia/Data-Stucture-and-Algorithms-Programs

CreateBST.c

A program to create a BST and inserting elements into the BST.

Create and insert in Binary Search Tree

---

Dynamic-Programming/LongestIncreasingSubsequence.java
README.md
Tree/CheckSubTree.java
Tree/LCS.java
Tree/MinimalTree.java
Tree/ValidateBST.java

Added Longest Increasing Subsequence program in Java

Added DP Program

---

LinkedList.java

Added the Linked List program

---

Linkedlist.c

Added a data structure progm for linked list.

---

MooreVoting.cpp

This algo is used to find the majority element of an array, if any.

Added Moore's Voting Algo

---

Kadane.cpp

Algorithm to find the maximum sum sub array.

Added Kadane's Algorithm

---

Brian_Karningam.cpp

This algo is used to find the number of set bits of a number

Added Brian and Kerningham Algorithm

---

Longest Palindrome Substring

Solution  for
Given a string s, find the longest palindromic substring in s. You may assume that the maximum length of s is 1000.

Create Longest Palindrome Substring

---

circular linked lists.c

using circular linked lists, traversing from last node to first node becomes easy
also ,in circular linked lists one can start from any node i.e. there is no fixed starting or end point

Create circular linked lists.c

---

doubly linked lists.c

doubly linked lists allows us to traverse in both direction
reduces time complexity of insertion and deletion operations

Create doubly linked lists.c

---

using linked list as stack

linked list can be used as stack
complexity reduces

Create using linked list as stack

---

Queue using linked list

queue operations using linked lists
it allows us to dynamically change size of queue

Create Queue using linked list

---

removeduplicates

c++ program  to remove duplicate elements from array

removeduplicate

---

Swaping Arrays.py

a jupyter notebook program that Contain Use of List data And then swapping There input and Giving Unique Outputs.
I Hope you Like it. Please make Sure that Everybody else Too get This. 
Then Accept My Contribution To This Repo.
Thank You!

Create Swaping Arrays.py

---

binary_search.cpp

binary_search

---

Bubble sort

Successfully contributed and do check this program

Added Bubble sort

---

ArrayReversal.cpp

To rotate an array left by d units

Added Array Reversal Algorithm

---

transpose of a matrix.c

Create transpose of a matrix.c

---

LinkedList.cpp

Implementation of Linked List using C++

LinkedList implementation

---

Minimum Square.java

Create Minimum Square.java

---

Kruskal’s Minimum Spanning Tree Algorithm

Given a connected and undirected graph, a spanning tree of that graph is a subgraph that is a tree and connects all the vertices together. A single graph can have many different spanning trees. A minimum spanning tree (MST) or minimum weight spanning tree for a weighted, connected and undirected graph is a spanning tree with weight less than or equal to the weight of every other spanning tree. The weight of a spanning tree is the sum of weights given to each edge of the spanning tree.

Kruskal’s Minimum Spanning Tree Algorithm

---

TwoWayLinearSearch.js

Two way Linear Search algorithm written in Javascript

Two way Linear Search 

---

ArrayMergeSorted

C program to merge two arrays in sorted order.

ArrayMergeSorted

---

Stack_Implementation.cpp

Added a stack implementation of STACK ADT using Linked List with basic functions :
1.PUSH
2.POP
3.DISPLAY

Added Stack_Implementation.cpp

---

program to convert a given binary tree to doubly linked list

Java program to convert a given binary tree to doubly linked list

Create program to convert a given binary tree to doubly linked list

---

linked list using Quicksort

A Java program to sort a linked list using Quicksort

Sort a linked list using Quicksort

---

binary heap.py

https://www.facebook.com/v3.1/dialog/share?display=popup&href=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3Dx084tfX4JnI%26feature%3Dshare&client_id=87741124305&ret=login&ext=1601913534&hash=AeYael-6mDYajuMo

Create binary heap.py

---

reverse a string using pointer

reverse a string using pointer

reverse a string using pointer

---

heap_sort.c

Subscribed Done..
FaceBook Post Done...
thank You in Advance

Heap Sort using C language

---

Converhull.cpp

Convex hull program in c++ for data structure and algorithms

Added a Convex Hull Program

---

Find start node of loop in linkedlist in java

Find start node of loop in linkedlist in java

Find start node of loop in linkedlist in java

---

Bubble Sort On Doubly Linked List

Java program to sort a doubly linked list using  bubble sort

Bubble Sort On Doubly Linked List

---

Merging Communities.py

I have added the "Merging Communities" program using Python of the Disjoint sets section of the Data structures

Added Merging Communities program

---

Jumping on the clouds.py

Here I have added the "Jumping on the clouds" program of Greedy Algorithm using python language

Added Jumping on the clouds

---

Karger’s algorithm for Minimum Cut | Set 1 (Introduction and Implementation)

Create Karger’s algorithm for Minimum Cut | Set 1 

---

Tower_Of_Hanoi.c

Tower Of Hanoi Using Recursion in C Language.

Tower Of Hanoi Using C

---

electricity bill programme

programme to calculate electricity bill

electricity bill programme

---

Odd-Even Sort (Brick Sort)

C++ program to sort an array using Odd-Even Sort.

Create Odd-Even Sort (Brick Sort)

---

Dfs of graph.cpp

Depth First Traversal (or Search) for a graph is similar to Depth First Traversal of a tree. The only catch here is, unlike trees, graphs may contain cycles, a node may be visited twice. To avoid processing a node more than once, use a boolean visited array.

Create Dfs of graph.cpp

---

dataS.java

added dataS

---

Bubblesort

Bubblesort

---

Merge sort

Merge sort code

---

0-1-Knapsack.cpp

0/1 Knapsack Dynamic Programming solution using C++

0-1Knapsack

---

count of numbers in array have k difference

Create count of numbers in array have k difference
